export const tabData = [
  {
    name: '12345',
    id: 1,
  },
  {
    name: '110非警情',
    id: 2,
  },
  {
    name: '网络舆情',
    id: 3,
  },
  {
    name: '一网共治APP',
    id: 4,
  },
  {
    name: '区长信箱',
    id: 5,
  },
  {
    name: '信访',
    id: 6,
  },
];

export const dataSource = [
  {
    id: '350',
    grid: '101007',
    detailed_location: '浦口区中海万锦熙岸',
    type: '投诉',
    event_category1: '社会事业',
    reporting_source: '卫生和计划生育委员会',
    event_category2: '公共卫生',
    event_category3: '卫生应急',
    name: '（医疗）急性传染病，突发公共卫生事件',
    detailes: '要求尽快告知防疫政策。',
    event_description:
      '【新型冠状病毒肺炎-离宁来宁防疫防控政策】浦口区中海万锦熙岸，有上海静安区和普陀区旅居史，12月1日来宁，社区也不联系自己，告知防疫政策，不认可，要求尽快告知防疫政策。',
    street_township: '浦口区',
    community: '江浦街道',
  },
  {
    id: '351',
    grid: '101007',
    detailed_location: '江苏省南京市浦口区',
    type: '投诉',
    event_category1: '民生保障',
    reporting_source: '人力资源和社会保障局',
    event_category2: '社会保障',
    event_category3: '医疗保险',
    name: '（医保）医疗保险，新农合',
    detailes: '联系医保局联系不上',
    event_description: '南京市医疗保障局官网上面的电话，在他们标注的工作时间内，都打不通',
    street_township: '浦口区',
    community: '医疗保障分局',
  },
  {
    id: '352',
    grid: '101007',
    detailed_location: '浦口区江浦街道老虎桥社区华山路',
    type: '投诉',
    event_category1: '城建城管',
    reporting_source: '城管局',
    event_category2: '市政设施',
    event_category3: '道路设施',
    name: '（道路）路面坑洼破损',
    detailes: '要求维修道路',
    event_description: '浦口区江浦街道老虎桥社区华山路，该处道路坑洼不平，无人维修，要求维修道路',
    street_township: '浦口区',
    community: '江浦街道',
  },
  {
    id: '353',
    grid: '101007',
    detailed_location: '浦口区杨山雅苑',
    type: '投诉',
    event_category1: '行业经济',
    reporting_source: '国土资源局',
    event_category2: '国土管理',
    event_category3: '国土管理',
    name: '土地所有权证、不动产权证',
    detailes: '要求办理不动产登记证',
    event_description:
      '浦口区杨山雅苑，此处是安置房，已经交房很久了，要办理不动产登记证，无法办理，不认可，要求办理不动产登记证。',
    street_township: '浦口区',
    community: '康居集团',
  },
  {
    id: '354',
    grid: '101007',
    detailed_location: '浦口区桥林街道民生巷第二排倒数第三家',
    type: '投诉',
    event_category1: '公共服务',
    reporting_source: '供水部门',
    event_category2: '供水服务管理',
    event_category3: '供水问题',
    name: '（供水）自来水水质、水压',
    detailes: '要求解决水压低问题',
    event_description: '浦口区桥林街道民生巷第二排倒数第三家，水压很小，要求解决水压低问题',
    street_township: '浦口区',
    community: '城建集团',
  },
  {
    id: '355',
    grid: '101007',
    detailed_location: '浦口区桥林街道林蒲社区杨郑组',
    type: '投诉',
    event_category1: '公共服务',
    reporting_source: '供水部门',
    event_category2: '供水服务管理',
    event_category3: '供水问题',
    name: '（供水）突发停水、爆管',
    detailes: '要求解决停水问题。',
    event_description:
      '浦口区桥林街道林蒲社区杨郑组，市民家里昨天开始停水，别人家有水，不清楚什么原因，要求解决停水问题。',
    street_township: '浦口区',
    community: '城建集团',
  },
  {
    id: '356',
    grid: '101007',
    detailed_location: '浦口区江浦街道新浦路105号江佑铂庭',
    type: '求助',
    event_category1: '城建城管',
    reporting_source: '住房保障和房产局',
    event_category2: '住房保障',
    event_category3: '房屋质量',
    name: '（房屋、小区）公共维修基金',
    detailes: '核实公共维修基金是否要做变更',
    event_description:
      '浦口区江浦街道新浦路105号江佑铂庭，市民反映购买二手房，核实公共维修基金是否要做变更',
    street_township: '浦口区',
    community: '房产局',
  },
  {
    id: '357',
    grid: '101007',
    detailed_location: '浦口区江浦街道巩固社区东华组',
    type: '求助',
    event_category1: '民生保障',
    reporting_source: '人力资源和社会保障局',
    event_category2: '社会保障',
    event_category3: '社会保险',
    name: '（社保）参保、缴费基数，退保',
    detailes: '希望核实缴费方式',
    event_description:
      '浦口区江浦街道巩固社区东华组，市民需要交城乡居民医保，希望核实缴费方式。（备注：市民要求社区回复）【该工单引用了 《市税务局关于城乡居民医疗保险缴费渠道和时间常见问题脚本 》;】',
    street_township: '浦口区',
    community: '江浦街道',
  },
  {
    id: '358',
    grid: '101007',
    detailed_location: '浦口区X203(杨山路)杨山雅苑二期',
    type: '投诉',
    event_category1: '城建城管',
    reporting_source: '城乡建设委员会',
    event_category2: '建筑单位管理',
    event_category3: '建筑民工权益',
    name: '农民工工资清欠',
    detailes: '要求支付工资',
    event_description:
      '浦口区X203(杨山路)杨山雅苑二期，市民反映自己在此处工地做木工，承包单位：宁浦公司，被拖欠工资1万多元，带班的负责人电话：18662280567。【该工单引用了 《市人社局劳动保障监察支队关于劳动保障监察机构及清欠办地址及电话常见问题脚本》;】',
    street_township: '浦口区',
    community: '康居集团',
  },
  {
    id: '359',
    grid: '101007',
    detailed_location: '浦口区江浦街道光明路与张墩路交叉口',
    type: '投诉',
    event_category1: '疑难诉求',
    reporting_source: '职责交叉/管理盲区',
    event_category2: '疑难诉求',
    event_category3: '道路设施（疑难）',
    name: '（道路）窨井，通讯井',
    detailes: '要求相关单位赔偿损失',
    event_description:
      '浦口区江浦街道光明路与张墩路交叉口，此处窨井没有盖子，市民车辆经过，现在车胎被划伤，要求相关单位赔偿损失。',
    street_township: '浦口区',
    community: '水务局',
  },
  {
    id: '360',
    grid: '101007',
    detailed_location: '浦口区江浦街道西水湾家园-二期25栋305室',
    type: '投诉',
    event_category1: '公共服务',
    reporting_source: '供水部门',
    event_category2: '供水服务管理',
    event_category3: '供水问题',
    name: '（供水）自来水水质、水压',
    detailes: '要求进行整改。',
    event_description:
      '浦口区江浦街道西水湾家园-二期25栋305室，该处自来水发白而且有漂白粉的味道，要求进行整改。',
    street_township: '浦口区',
    community: '城建集团',
  },
  {
    id: '361',
    grid: '101007',
    detailed_location: '浦口区江浦街道',
    type: '求助',
    event_category1: '城建城管',
    reporting_source: '住房保障和房产局',
    event_category2: '房产管理',
    event_category3: '房产交易',
    name: '（房屋）房产交易',
    detailes: '核实此处安置房怎么过户',
    event_description: '浦口区江浦街道，核实此处安置房怎么过户。',
    street_township: '浦口区',
    community: '规划和自然资源分局',
  },
  {
    id: '362',
    grid: '101007',
    detailed_location: '浦口区张墩路中海万锦熙岸-二期星原护肤造型',
    type: '投诉',
    event_category1: '市场监管',
    reporting_source: '工商局',
    event_category2: '市场管理',
    event_category3: '消费维权',
    name: '（消费者）服务质量问题',
    detailes: '要求投诉店铺强制消费',
    event_description:
      '浦口区张墩路中海万锦熙岸二期星原护肤造型，市民原先在喵斯充值500元，现在由该店接手，市民去消费，但是需要重新充值，否则无法使用余额，要求投诉店铺强制消费。',
    street_township: '浦口区',
    community: '商务局',
  },
  {
    id: '363',
    grid: '101007',
    detailed_location: '浦口区江浦街道狮山路江山郡极兔速递旁回收点',
    type: '投诉',
    event_category1: '城建城管',
    reporting_source: '城管局',
    event_category2: '市容管理',
    event_category3: '占道经营',
    name: '（占道）固定门面倚门出摊',
    detailes: '要求取缔倚门出摊。',
    event_description:
      '浦口区江浦街道狮山路江山郡极兔速递旁回收点，市民反映此处回收点占道经营，对此不认可，要求取缔倚门出摊。',
    street_township: '浦口区',
    community: '江浦街道',
  },
  {
    id: '364',
    grid: '101007',
    detailed_location: '浦口区桥林街道',
    type: '投诉',
    event_category1: '公共服务',
    reporting_source: '供水部门',
    event_category2: '供水设施管理',
    event_category3: '供水设施建设',
    name: '（供水）供水施工工地管理',
    detailes: '要求施工单位，恢复农田苗木',
    event_description: '桥林自来水项目一期施工，浦乌路段，破坏我家农田苗木，',
    street_township: '浦口区',
    community: '城建集团',
  },
  {
    id: '365',
    grid: '101007',
    detailed_location: '浦口区江浦街道东方万汇国际公寓',
    type: '投诉',
    event_category1: '城建城管',
    reporting_source: '住房保障和房产局',
    event_category2: '物业管理',
    event_category3: '物业管理',
    name: '（小区）物业服务、收费',
    detailes: '要求告知物业的做法是否合法。',
    event_description:
      '浦口区江浦街道东方万汇国际公寓，停车费和物业费现在是捆绑缴纳，市民表示之前都是分开缴纳的，要求告知物业的做法是否合法。',
    street_township: '浦口区',
    community: '江浦街道',
  },
  {
    id: '366',
    grid: '101007',
    detailed_location: '浦口区江浦街道正荣润棠府6号楼2栋1803室',
    type: '投诉',
    event_category1: '城建城管',
    reporting_source: '住房保障和房产局',
    event_category2: '房产管理',
    event_category3: '房产交易',
    name: '（房屋）房产纠纷',
    detailes: '要求尽快备案',
    event_description:
      '浦口区江浦街道正荣润棠府6号楼2栋1803室，市民是此处业主，开发商至今没有备案，要求尽快备案。',
    street_township: '浦口区',
    community: '房产局',
  },
  {
    id: '367',
    grid: '101007',
    detailed_location: '浦口区江浦街道城南河、七里河',
    type: '求助',
    event_category1: '行业经济',
    reporting_source: '农业委员会',
    event_category2: '农业生产管理',
    event_category3: '农林牧副渔',
    name: '（农村）农林牧副渔',
    detailes: '希望核实此处是否属于禁捕区域、非禁用渔具是否可以使用',
    event_description:
      '浦口区江浦街道城南河、七里河，希望核实此处是否属于禁捕区域、非禁用渔具是否可以使用。',
    street_township: '浦口区',
    community: '农业农村局',
  },
  {
    id: '368',
    grid: '101007',
    detailed_location: '浦口区江浦街道华光社区北江豪庭',
    type: '求助',
    event_category1: '城建城管',
    reporting_source: '住房保障和房产局',
    event_category2: '物业管理',
    event_category3: '物业管理',
    name: '（小区）物业设施使用、维护',
    detailes: '希望核实如何减免。',
    event_description:
      '浦口区江浦街道华光社区北江豪庭，车辆在小区内发生过碰擦，当时122出警了，有部分原因是因为物业整修道路导致的，楼层葛主管表示赔偿无法通过正常渠道支付，可以在第二年车位费上进行减免，希望核实如何减免。',
    street_township: '浦口区',
    community: '江浦街道',
  },
  {
    id: '369',
    grid: '101007',
    detailed_location: '浦口区海都路金盛田广场二期门口',
    type: '投诉',
    event_category1: '城建城管',
    reporting_source: '城管局',
    event_category2: '市容管理',
    event_category3: '停车管理',
    name: '（停车）非主次干道违停违章停车管理',
    detailes: '【110】要求处理违停车辆',
    event_description:
      '浦口区海都路金盛田广场二期门口，反映很多车违停，要求处理违停车辆。已告知报警人警情流转12345热线处理，报警人表示认可。【公安转接的非警务、非紧急类警情】【违停】(接警台电话：28735)（交警反馈，重新生单）',
    street_township: '浦口区',
    community: '江浦街道',
  },
  {
    id: '370',
    grid: '101007',
    detailed_location: '浦口区永宁街道岔琥路29号',
    type: '投诉',
    event_category1: '社会事业',
    reporting_source: '卫生和计划生育委员会',
    event_category2: '公共卫生',
    event_category3: '卫生应急',
    name: '（医疗）急性传染病，突发公共卫生事件',
    detailes: '要求简化程序，只提供一个就够了',
    event_description:
      '【新型冠状病毒肺炎-公共场所管理】浦口区永宁街道岔琥路29号，此处旅游度假区检查疫情健康码查询繁琐，需要同时出具苏康码和行程码。',
    street_township: '浦口区',
    community: '城建集团',
  },
  {
    id: '371',
    grid: '101007',
    detailed_location: '浦口区江浦街道老海校彤德莱火锅(江浦店)',
    type: '投诉',
    event_category1: '市场监管',
    reporting_source: '工商局',
    event_category2: '市场管理',
    event_category3: '消费维权',
    name: '103103100101104',
    detailes: '要求退款',
    event_description: '浦口区江浦街道老海校彤德莱火锅(江浦店)，市民反映充值，现在店关门了。',
    street_township: '浦口区',
    community: '商务局',
  },
  {
    id: '372',
    grid: '101007',
    detailed_location: '浦口区桥林街道北菜场小区',
    type: '投诉',
    event_category1: '城建城管',
    reporting_source: '城管局',
    event_category2: '市容管理',
    event_category3: '占道经营',
    name: '（占道）固定门面倚门出摊',
    detailes: '要求查处倚门出摊',
    event_description: '浦口区桥林街道北菜场小区，该处有商店（怡萤果业）倚门出摊，影响交通、环境。',
    street_township: '浦口区',
    community: '桥林街道',
  },
  {
    id: '373',
    grid: '101007',
    detailed_location: '浦口区桥林街道丝兰湖商业中心3楼星悦荟KTV',
    type: '投诉',
    event_category1: '市场监管',
    reporting_source: '工商局',
    event_category2: '市场管理',
    event_category3: '消费维权',
    name: '（消费者）服务质量问题',
    detailes: '投诉店家欺骗消费者',
    event_description:
      '浦口区桥林街道丝兰湖商业中心3楼星悦荟KTV，市民在美团订的套餐，但是现在商家没开门，平台写的是下午1点到夜间2点，但是市民一点就来了，到现在还没开门，打联系电话无人接听。',
    street_township: '浦口区',
    community: '市场监管局',
  },
  {
    id: '374',
    grid: '101007',
    detailed_location: '浦口区江浦街道缔景名苑一米阳光咖啡店',
    type: '投诉',
    event_category1: '市场监管',
    reporting_source: '工商局',
    event_category2: '市场管理',
    event_category3: '消费维权',
    name: '103103100101104',
    detailes: '要求退费',
    event_description:
      '浦口区江浦街道缔景名苑一米阳光咖啡店，市民在此处充值了2000元，没有消费，现在工作调动不在此处了，申请退费，商家不同意',
    street_township: '浦口区',
    community: '商务局',
  },
  {
    id: '375',
    grid: '101007',
    detailed_location: '浦口区江浦街道',
    type: '求助',
    event_category1: '民生保障',
    reporting_source: '人力资源和社会保障局',
    event_category2: '社会保障',
    event_category3: '医疗保险',
    name: '（医保）医疗保险，新农合',
    detailes: '要求核实如何缴纳学生医保以及多收的费用是否可以退还',
    event_description:
      '浦口区江浦街道，市民孩子户口在此处，刚满18岁，人在徐州上大学，市民给孩子参保，缴纳了560元，但是应该享受学生医保，要求核实如何缴纳学生医保以及多收的费用是否可以退还。身份证：34182520030415003X',
    street_township: '浦口区',
    community: '社保中心',
  },
  {
    id: '376',
    grid: '101007',
    detailed_location: '浦口区江浦街道巩固社区',
    type: '求助',
    event_category1: '社会事业',
    reporting_source: '卫生和计划生育委员会',
    event_category2: '公共卫生',
    event_category3: '疾病控制',
    name: '（医疗）疫苗，计划免疫',
    detailes: '核实接种疫苗问题',
    event_description:
      '【新型冠状病毒肺炎-新冠疫苗】浦口区江浦街道巩固社区，接种过第一针新冠疫苗，需要注射第二针。',
    street_township: '浦口区',
    community: '江浦街道',
  },
  {
    id: '377',
    grid: '101007',
    detailed_location:
      '浦口区江浦街道五合路和园达路交叉口南京国家农创园公共创新平台B座7楼天邦食品股份有限公司',
    type: '投诉',
    event_category1: '民生保障',
    reporting_source: '人力资源和社会保障局',
    event_category2: '人力资源',
    event_category3: '劳动关系',
    name: '企业职工工资问题和劳动维权',
    detailes: '要求支付差旅费。',
    event_description:
      '浦口区江浦街道五合路和园达路交叉口南京国家农创园公共创新平台B座7楼天邦食品股份有限公司，市民是此处项目经理，公司拖欠5月到10月的差旅费，对此不认可，要求支付差旅费。',
    street_township: '浦口区',
    community: '人社局',
  },
  {
    id: '378',
    grid: '101007',
    detailed_location: '浦口区桥林街道吴江社区',
    type: '求助',
    event_category1: '行业经济',
    reporting_source: '国土资源局',
    event_category2: '国土管理',
    event_category3: '国土管理',
    name: '（土地）集体土地征地、征地补偿、拆迁',
    detailes: '希望核实没有发放的原因。',
    event_description:
      '浦口区桥林街道吴江社区，市民反映家里老人（胡敬翠）之前田亩被征收，每月都有田亩补贴，1000多元，11月份没有发放短信通知，希望核实没有发放的原因。',
    street_township: '浦口区',
    community: '桥林街道',
  },
  {
    id: '379',
    grid: '101007',
    detailed_location: '浦口区江浦街道同心社区新浦路111号中建国熙台',
    type: '投诉',
    event_category1: '城建城管',
    reporting_source: '住房保障和房产局',
    event_category2: '物业管理',
    event_category3: '物业管理',
    name: '（小区）物业设施使用、维护',
    detailes: '要求禁止出租给商铺',
    event_description:
      '浦口区江浦街道同心社区新浦路111号中建国熙台，小区物业将物业用房出租给菜鸟驿站，使用小区居民公摊电费，市民对此不认可，要求禁止出租给商铺。',
    street_township: '浦口区',
    community: '江浦街道',
  },
];

export const dataSource1 = [
  {
    id: '1',
    name: '江浦街道',
    type: '未办结',
    detailes: '110非警情案件',
  },
  {
    id: '2',
    name: '联勤指挥中心',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '3',
    name: '江浦街道',
    type: '未办结',
    detailes: '110非警情案件',
  },
  {
    id: '4',
    name: '江浦街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '5',
    name: '江浦街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '6',
    name: '江浦街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '7',
    name: '联勤指挥中心',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '8',
    name: '江浦街道',
    type: '未办结',
    detailes: '110非警情案件',
  },
  {
    id: '9',
    name: '联勤指挥中心',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '10',
    name: '江浦街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '11',
    name: '桥林街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '12',
    name: '桥林街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '13',
    name: '江浦街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '14',
    name: '联勤指挥中心',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '15',
    name: '江浦街道',
    type: '未办结',
    detailes: '110非警情案件',
  },
  {
    id: '16',
    name: '江浦街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '17',
    name: '联勤指挥中心',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '18',
    name: '联勤指挥中心',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '19',
    name: '江浦街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '20',
    name: '桥林街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '21',
    name: '江浦街道',
    type: '未办结',
    detailes: '110非警情案件',
  },
  {
    id: '22',
    name: '江浦街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '23',
    name: '江浦街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '24',
    name: '江浦街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '25',
    name: '桥林街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '26',
    name: '江浦街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '27',
    name: '联勤指挥中心',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '28',
    name: '联勤指挥中心',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '29',
    name: '江浦街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '30',
    name: '联勤指挥中心',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '31',
    name: '江浦街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '32',
    name: '江浦街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '33',
    name: '联勤指挥中心',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '34',
    name: '桥林街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
];
export const dataSource2 = [
  {
    id: '35',
    name: '汤泉街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '36',
    name: '联勤指挥中心',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '37',
    name: '江浦街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '38',
    name: '联勤指挥中心',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '39',
    name: '江浦街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '40',
    name: '联勤指挥中心',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '41',
    name: '江浦街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
  {
    id: '42',
    name: '江浦街道',
    type: '已办结',
    detailes: '110非警情案件',
  },
];
export const dataSource3 = [
  {
    id: '1',
    name: '联勤指挥中心',
    type: '未办结',
    detailes: '星甸派出所顾坝B区有流浪狗出没希望处理',
  },
  {
    id: '2',
    name: '联勤指挥中心',
    type: '未办结',
    detailes: '咨询星甸派出所户籍周末可以办理业务吗',
  },
  {
    id: '3',
    name: '江浦街道',
    type: '未办结',
    detailes: '车辆亚青路白马社区入口处违停',
  },
  {
    id: '4',
    name: '联勤指挥中心',
    type: '未办结',
    detailes: '咨询星甸派出所港澳通行证办理需要那些材料',
  },
  {
    id: '5',
    name: '联勤指挥中心',
    type: '未办结',
    detailes: '咨询星甸派出所居住证遗失补办需要钱吗',
  },
  {
    id: '6',
    name: '桥林街道',
    type: '未办结',
    detailes: '乌江社区路口斑马线停了一辆机动车，路口本来就小希望有人将其处理，不然有安全隐患',
  },
  {
    id: '7',
    name: '桥林街道',
    type: '已办结',
    detailes: '堆放的树枝影响卫生环境和人员出行。',
  },
  {
    id: '8',
    name: '桥林街道',
    type: '已办结',
    detailes: '周营村陈云组自家门前堆放树棍，影响环境。',
  },
  {
    id: '9',
    name: '桥林街道',
    type: '已办结',
    detailes: '周营村雷营组房屋外侧堆放大量树枝，影响出行。',
  },
  {
    id: '10',
    name: '桥林街道',
    type: '未办结',
    detailes: '桥林街道福音社区南街有个高压电表盒盖子没有盖好，有安全隐患，希望有人赶紧处理。',
  },
  {
    id: '11',
    name: '江浦街道',
    type: '已办结',
    detailes: '汽车违停',
  },
  {
    id: '12',
    name: '桥林街道',
    type: '未办结',
    detailes: '明因寺民旺小区28栋二单元楼道里停放非机动车，影响人员出进困难，请相关部门处理。',
  },
  {
    id: '13',
    name: '桥林街道',
    type: '未办结',
    detailes: '我是林蒲社区居民，林蒲社区道路上有车辆违规停放，请社区前来处理',
  },
  {
    id: '14',
    name: '桥林街道',
    type: '未办结',
    detailes: '我是林蒲社区居民，林蒲社区道路上有车辆违规停放，请社区前来处理',
  },
  {
    id: '15',
    name: '联勤指挥中心',
    type: '已办结',
    detailes: '揽月幼稚园门前违停',
  },
  {
    id: '16',
    name: '江浦街道',
    type: '已办结',
    detailes: '北江豪庭东门违停',
  },
  {
    id: '17',
    name: '桥林街道',
    type: '已办结',
    detailes:
      '桥林经济开发区：我们安置房钱已交一个星期了，为什么到现在还不通知我们拿房呢？过度费和拆迁的利息都算清了，希望政府有关部门能及时处理一下',
  },
  {
    id: '18',
    name: '联勤指挥中心',
    type: '已办结',
    detailes: '中圣北街2号违停',
  },
  {
    id: '19',
    name: '联勤指挥中心',
    type: '已办结',
    detailes: '中圣南街80号供电局小区门口违停。',
  },
  {
    id: '20',
    name: '联勤指挥中心',
    type: '已办结',
    detailes: '中圣北街2号违停',
  },
  {
    id: '21',
    name: '江浦街道',
    type: '已办结',
    detailes: '白马路沿山大道路口信号灯不亮',
  },
  {
    id: '22',
    name: '联勤指挥中心',
    type: '已办结',
    detailes: '象山路1号车辆违停。',
  },
  {
    id: '23',
    name: '江浦街道',
    type: '已办结',
    detailes: '珠泉路3一1号有车辆违停',
  },
];
export const dataSource4 = [
  {
    id: '1',
    name: '国土局与南京广佳置业开发商有纠纷，把我得房子查封，不让过户，我有家不能回',
    type: '不公开',
    detailes: '南京市规划和自然资源局浦口分局',
  },
  {
    id: '2',
    name: '金雁湖社区中心B座超市、餐饮什么时候可以运营？',
    type: '不公开',
    detailes: '浦口高新区',
  },
  {
    id: '3',
    name: '要求退还会员卡余额，维护消费者正当权益！',
    type: '不公开',
    detailes: '浦口区商务局',
  },
  {
    id: '4',
    name: '敬爱的区政府领导，林山雅苑有人非法在居民楼地下室创办面粉加工黑作坊',
    type: '不公开',
    detailes: '浦口区人民政府桥林街道办事处',
  },
  {
    id: '5',
    name: '万汇城南区商业项目何时停工报备？现场的脚手架现阶段如何才能拆除止损？',
    type: '不公开',
    detailes: '浦口高新区',
  },
  {
    id: '6',
    name: '北花园路中小学建设情况？',
    type: '不公开',
    detailes: '浦口区国资集团',
  },
  {
    id: '7',
    name: '关于咨询北花园路小学事宜',
    type: '不公开',
    detailes: '浦口区国资集团',
  },
  {
    id: '8',
    name: '拆迁过渡费',
    type: '不公开',
    detailes: '浦口区人民政府桥林街道办事处',
  },
  {
    id: '9',
    name: '南京市浦口区林景尊园违规交付问题',
    type: '不公开',
    detailes: '浦口区城乡建设局',
  },
  {
    id: '10',
    name: '浦口区住建局联合开发商欺骗老百姓',
    type: '不公开',
    detailes: '浦口区城乡建设局',
  },
  {
    id: '11',
    name: '通宇林景开发商、区住建局、广电局、工信局、中燃公司',
    type: '不公开',
    detailes: '浦口区城乡建设局',
  },
  {
    id: '12',
    name: '立新路幼儿园建设问题',
    type: '不公开',
    detailes: '浦口区教育局',
  },
  {
    id: '13',
    name: '凤滁路和天浦路交汇处交警过多',
    type: '不公开',
    detailes: '南京市公安局浦口分局',
  },
  {
    id: '14',
    name: '恳请区委、区政府救人求稳定',
    type: '不公开',
    detailes: '浦口开发区',
  },
  {
    id: '15',
    name: '极乐寺何时拆迁',
    type: '不公开',
    detailes: '南京市浦口区拆迁管理中心',
  },
  {
    id: '16',
    name: '312国道 海峡大道附近的加油站何时拆除',
    type: '不公开',
    detailes: '浦口区人民政府江浦街道办事处',
  },
  {
    id: '17',
    name: '道路建设咨询',
    type: '不公开',
    detailes: '浦口高新区',
  },
  {
    id: '18',
    name: '预决算报告',
    type: '公开',
    detailes: '浦口区政府办',
  },
  {
    id: '19',
    name: '公共图书馆',
    type: '公开',
    detailes: '浦口区文化和旅游局',
  },
  {
    id: '20',
    name: '关于江浦街道新浦路路段的路面维护及公共自行车站点的几点建议',
    type: '不公开',
    detailes: '浦口区城建集团',
  },
  {
    id: '21',
    name: '新浦路修路交通混乱问题',
    type: '不公开',
    detailes: '浦口区城建集团',
  },
  {
    id: '22',
    name: '汤泉街道龙郢小区房产证办理咨询',
    type: '不公开',
    detailes: '浦口区人民政府汤泉街道办事处',
  },
];

export const dataSource5 = [
  {
    id: '23',
    name: '关于发放“光荣之家”牌匾的咨询',
    type: '不公开',
    detailes: '浦口区人民政府江浦街道办事处',
  },
  {
    id: '24',
    name: '浦口区江浦街道高旺脏乱差没人管',
    type: '不公开',
    detailes: '浦口区人民政府江浦街道办事处',
  },
  {
    id: '25',
    name:
      '关于进一步扩大浦口区养犬重点管理区范围，切实加强养犬管理，充分保障人民群众人身健康与安全的建议',
    type: '不公开',
    detailes: '南京市公安局浦口分局',
  },
  {
    id: '26',
    name: '关于万汇城南区商业一直烂尾的事宜',
    type: '不公开',
    detailes: '浦口高新区',
  },
  {
    id: '27',
    name: '一封信',
    type: '不公开',
    detailes: '浦口区人民政府江浦街道办事处',
  },
  {
    id: '28',
    name: '举报非法夜间马路市场，噪音严重扰民',
    type: '不公开',
    detailes: '浦口区人民政府江浦街道办事处',
  },
  {
    id: '29',
    name: '我区违法行为举报',
    type: '不公开',
    detailes: '南京市公安局浦口分局',
  },
  {
    id: '30',
    name: '浦口高新区部分民生问题咨询',
    type: '公开',
    detailes: '浦口高新区',
  },
  {
    id: '31',
    name: '拆迁安置房',
    type: '不公开',
    detailes: '浦口区人民政府汤泉街道办事处',
  },
  {
    id: '32',
    name: '咨询围挡施工具体情况',
    type: '不公开',
    detailes: '浦口区人民政府江浦街道办事处',
  },
  {
    id: '33',
    name: '江浦街道巩固西华组拆迁安置',
    type: '不公开',
    detailes: '浦口区人民政府江浦街道办事处',
  },
  {
    id: '34',
    name: '桥林姚庄组安置房',
    type: '不公开',
    detailes: '浦口区人民政府桥林街道办事处',
  },
  {
    id: '35',
    name: '关于桥林林山雅苑安置房何时安置的问题',
    type: '不公开',
    detailes: '浦口区人民政府桥林街道办事处',
  },
  {
    id: '36',
    name: '有关浦乌路快速化改造高架与隧道规划方案的咨询问题',
    type: '不公开',
    detailes: '浦口区交通运输局',
  },
];
